title: The Things We Can't Perceive Are Endless
author: sbackon
description: > # this means to ignore newlines until "baseurl:"
  There are worlds so small we can't see. There are worlds so quiete we can't hear.
  There are worlds so miniscule we can't feel.

# social links
github_username:  sbackon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
